In [14]:
import glob
import numpy as np
from pprint import pprint 
folder=glob.glob("./data/*")
folder=sorted(folder, key=lambda s: s.lower())
for f in folder:
    print f

./data/AAFREEN
./data/aanyaa cotton
./data/aditisitara
./data/AFREEN
./data/AKIRA
./data/ananya
./data/ANNIKA
./data/ARABELLA
./data/ayesha
./data/AYESHA 5
./data/ayesha baby
./data/AYSHA PAT HOUSE 32
./data/babydoll
./data/babydoll 16
./data/babydoll 22
./data/BALAJI SPARK
./data/BANDHAN
./data/BATIK
./data/BATIK KAPIL
./data/BATIK PRIYANKA
./data/BREEZER
./data/BREZZER
./data/bull bull
./data/Celebration 2
./data/chief guest
./data/chief guest2
./data/classy cotton
./data/cotton plus 3
./data/DD 2
./data/DD 3
./data/DD 4
./data/DD 5
./data/DD 6
./data/DD 7
./data/DD 8
./data/DD 9
./data/DEEPTEX BANDNI
./data/DEEPTEX BANDNI CHUNARI
./data/DEVI BATIK
./data/dolly 11
./data/DOLLY 13
./data/DOLLY 15
./data/DOLLY 19
./data/DOLLY BATIK
./data/elegant ayesha 3
./data/feelings
./data/GANESA 13
./data/GANESA PATIALA 1
./data/GANESA PATIALA 2
./data/GAZAL
./data/HOT SHOT
./data/HOTSTAR
./data/ISHQ E AYESHA 4
./data/jalwa 1
./data/jalwa 2
./data/jodha
./data/jodha 2
./data/jugni
./data/KANISHKA

In [17]:
price=np.loadtxt('price.txt')
print price

[[ 495.    1.    1.    0.]
 [ 405.    1.    1.    0.]
 [ 640.    0.    2.    0.]
 [ 540.    1.    1.    0.]
 [ 485.    1.   10.    0.]
 [ 310.    1.    2.    0.]
 [ 310.    1.    2.    1.]
 [ 350.    1.    2.    0.]
 [ 870.    0.   10.    1.]
 [ 830.    0.   10.    1.]
 [ 535.    1.   10.    1.]
 [ 914.    0.   10.    0.]
 [ 555.    1.    1.    1.]
 [ 535.    1.    1.    1.]
 [ 555.    1.   10.    0.]
 [ 465.    0.   10.    0.]
 [ 310.    1.    2.    0.]
 [ 460.    1.    0.    0.]
 [ 430.    1.    0.    1.]
 [ 405.    1.    0.    0.]
 [ 345.    0.    2.    1.]
 [ 685.    1.   10.    0.]
 [ 430.    1.   10.    0.]
 [ 610.    0.   10.    1.]
 [ 400.    1.    2.    0.]
 [ 385.    1.    2.    0.]
 [ 320.    1.    2.    0.]
 [ 605.    0.   10.    0.]
 [ 455.    1.   10.    0.]
 [ 455.    1.   10.    1.]
 [ 450.    1.    1.    0.]
 [ 445.    1.    1.    0.]
 [ 445.    1.    1.    1.]
 [ 445.    1.    1.    0.]
 [ 455.    1.   10.    0.]
 [ 455.    1.   10.    0.]
 [ 345.    1.    0.    0.]
 

In [26]:
from PIL import Image
im=[]
p=[]
w=[]
h=[]
c=[]
q=0
for f in folder:
    files=glob.glob(f+'/*.jpg')
    for j in files:
        img=Image.open(j)
        #print img.size
        img=img.resize((30,30), Image.ANTIALIAS)
        newim=np.asarray(img)
        '''break
        b=plt.imread(i)
        '''
        b=newim.flatten()
        im.append(b)
        p.append(price[q][0])
        w.append(price[q][1])
        h.append(price[q][2])
        c.append(price[q][3])
    q=q+1

print im[0],p[0],w[0],h[0],c[0]

[255 255 255 ..., 255 255 255] 495.0 1.0 1.0 0.0


In [52]:
print len(im)
from sklearn.svm import SVR
svr = SVR(kernel='rbf', C=1e3, gamma=0.1)

1756


In [74]:
oe1=0.0
oe2=0.0
for i in range(10):
    from keras.models import Sequential
    from keras.layers import Dense, Activation
    m=Sequential()
    m.add(Dense(600,input_dim=2700))
    m.add(Activation('relu'))
    m.add(Dense(100))
    m.add(Activation('relu'))
    m.add(Dense(1))
    m.add(Activation('relu'))

    m.compile(loss='mean_absolute_percentage_error',optimizer='adagrad')
    
    #print len(im)
    from sklearn.svm import SVR
    svr = SVR(kernel='rbf', C=1e3, gamma=0.1)

    
    trainx=[]
    trainy=[]
    testx=[]
    testy=[]
    for j in range(1750):
        if j < i*175 or j>=i*175 + 175:
            temp=[]
            for l in range(2700):
                temp.append(float(im[j][l])/255)
            trainx.append(temp)
            trainy.append([p[j]])
    for j in range(i*175,i*175 + 175):
        temp=[]
        for l in range(2700):
            temp.append(float(im[j][l])/255)
        testx.append(temp)
    #testx=[im[x]/255 for x in range(i*175,i*175 + 175)]
    for j in range(i*175,i*175 + 175):
        testy.append(p[j])
    #testy=[p[x] for x in range(i*175,i*175 + 175)]    
    print np.shape(trainx)
    m.fit(trainx,trainy, epochs=10, batch_size=32)
    tp=m.predict(trainx,batch_size=16)
    #print len(tp)
    newtrainx=[]
    k=0
    #print len(tp)
    for j in range(1750):
        if j < i*175 or j>=i*175 + 175:
            b=[tp[k][0]]
            b.append(w[j])
            b.append(h[j])
            b.append(c[j])
            newtrainx.append(b)
            k=k+1
    svr.fit(newtrainx,trainy)
    tp=m.predict(testx,batch_size=32)
    acc=0.0
    #print ty
    for j in range(len(tp)):
        acc+=(abs(testy[j]-tp[j])/testy[j])*100
    acc=acc/len(tp)
    print acc
    oe1+=acc
    
    newtest=[]
    k=0
    for j in range(i*175,i*175+175):
        b=[tp[k][0]]
        k=k+1
        b.append(w[j])
        b.append(h[j])
        b.append(c[j])
        newtest.append(b)
    ty=svr.predict(newtest)
    acc=0.0
    #print ty
    for j in range(len(ty)):
        acc+=(abs(testy[j]-ty[j])/testy[j])*100
    acc=acc/len(ty)
    print acc
    oe2+=acc

(1575, 2700)
Epoch 1/10
1575/1575 [==============================] - 1s - loss: 33.4571      

In [75]:
print oe1/10
print oe2/10

[ 28.22785568]
22.3143655823


In [78]:
oe1=0.0
oe2=0.0
for i in range(10):
    from keras.models import Sequential
    from keras.layers import Dense, Activation
    m=Sequential()
    m.add(Dense(600,input_dim=2700))
    m.add(Activation('relu'))
    m.add(Dense(100))
    m.add(Activation('relu'))
    m.add(Dense(1))
    m.add(Activation('relu'))

    m.compile(loss='mean_absolute_percentage_error',optimizer='sgd')
    
    #print len(im)
    from sklearn.svm import SVR
    svr = SVR(kernel='rbf', C=1e3, gamma=0.1)

    
    trainx=[]
    trainy=[]
    testx=[]
    testy=[]
    for j in range(1750):
        if j < i*175 or j>=i*175 + 175:
            temp=[]
            for l in range(2700):
                temp.append(float(im[j][l])/255)
            trainx.append(temp)
            trainy.append([p[j]])
    for j in range(i*175,i*175 + 175):
        temp=[]
        for l in range(2700):
            temp.append(float(im[j][l])/255)
        testx.append(temp)
    #testx=[im[x]/255 for x in range(i*175,i*175 + 175)]
    for j in range(i*175,i*175 + 175):
        testy.append(p[j])
    #testy=[p[x] for x in range(i*175,i*175 + 175)]    
    print np.shape(trainx)
    m.fit(trainx,trainy, epochs=10, batch_size=32)
    tp=m.predict(trainx,batch_size=16)
    #print len(tp)
    newtrainx=[]
    k=0
    #print len(tp)
    for j in range(1750):
        if j < i*175 or j>=i*175 + 175:
            b=[tp[k][0]]
            b.append(w[j])
            b.append(h[j])
            b.append(c[j])
            newtrainx.append(b)
            k=k+1
    svr.fit(newtrainx,trainy)
    tp=m.predict(testx,batch_size=32)
    acc=0.0
    #print ty
    for j in range(len(tp)):
        acc+=(abs(testy[j]-tp[j])/testy[j])*100
    acc=acc/len(tp)
    print acc
    oe1+=acc
    
    newtest=[]
    k=0
    for j in range(i*175,i*175+175):
        b=[tp[k][0]]
        k=k+1
        b.append(w[j])
        b.append(h[j])
        b.append(c[j])
        newtest.append(b)
    ty=svr.predict(newtest)
    acc=0.0
    #print ty
    for j in range(len(ty)):
        acc+=(abs(testy[j]-ty[j])/testy[j])*100
    acc=acc/len(ty)
    print acc
    oe2+=acc

(1575, 2700)
Epoch 1/10
1575/1575 [==============================] - 0s - loss: 54.9342      
Epoch 2/10
1575/1575 

In [79]:
print oe1/10
print oe2/10

[ 48.73715973]
21.4495591463


In [80]:
print ty

[ 792.4425309   768.53839033  676.59174491  592.4112082   640.05853641
  781.38047251  811.96914688  776.91484929  809.50655874  331.00476436
  371.62278954  403.5966027   362.26467941  324.3859366   348.99773769
  350.49588398  367.26611185  335.4591817   328.46266748  394.23117083
  400.09292775  369.55942696  394.25884565  324.96797658  731.43432883
  657.80205995  828.11365244  647.29142384  684.81288602  981.21289267
  815.75002174  543.8716752   491.49937942  360.94420948  356.06939583
  327.11756646  374.41022646  361.90935003  382.36761088  370.330859
  555.46375483  911.82292724  585.65908578  507.76508145  709.18474183
  782.92430192  635.22966112  699.95241884  690.09140519  624.15555223
  563.75890059  790.78553547  749.99203309  597.20763552  355.28219253
  487.80924209  882.84409368  706.21991354  786.88590381  625.17633303
  486.5990475   694.4067499   846.84220612  684.79505767  750.00129679
  344.1390945   510.95706964  378.12712319  461.2799192   519.76022449
  332.47

In [81]:
print testy

[810.0, 810.0, 810.0, 810.0, 810.0, 810.0, 810.0, 810.0, 810.0, 370.0, 370.0, 370.0, 370.0, 370.0, 370.0, 370.0, 370.0, 320.0, 320.0, 320.0, 320.0, 320.0, 320.0, 320.0, 610.0, 610.0, 610.0, 610.0, 610.0, 610.0, 610.0, 610.0, 610.0, 360.0, 360.0, 360.0, 360.0, 360.0, 360.0, 360.0, 260.0, 260.0, 260.0, 260.0, 260.0, 260.0, 260.0, 260.0, 260.0, 260.0, 260.0, 260.0, 260.0, 260.0, 260.0, 260.0, 260.0, 260.0, 260.0, 260.0, 260.0, 260.0, 260.0, 260.0, 260.0, 260.0, 260.0, 330.0, 330.0, 330.0, 330.0, 330.0, 330.0, 330.0, 330.0, 330.0, 330.0, 330.0, 250.0, 250.0, 250.0, 250.0, 250.0, 250.0, 250.0, 250.0, 250.0, 250.0, 250.0, 250.0, 685.0, 685.0, 685.0, 685.0, 685.0, 685.0, 685.0, 685.0, 685.0, 685.0, 685.0, 685.0, 450.0, 450.0, 450.0, 450.0, 450.0, 450.0, 450.0, 450.0, 450.0, 450.0, 450.0, 450.0, 450.0, 285.0, 285.0, 285.0, 285.0, 285.0, 285.0, 285.0, 285.0, 285.0, 285.0, 285.0, 285.0, 285.0, 285.0, 285.0, 360.0, 360.0, 360.0, 360.0, 360.0, 360.0, 360.0, 360.0, 360.0, 360.0, 360.0, 360.0, 360.0