In [1]:
import glob
import numpy as np
from pprint import pprint 
folder=glob.glob("./data/*")
folder=sorted(folder, key=lambda s: s.lower())
for f in folder:
    print f

./data/AAFREEN
./data/aanyaa cotton
./data/aditisitara
./data/AFREEN
./data/AKIRA
./data/ananya
./data/ANNIKA
./data/ARABELLA
./data/ayesha
./data/AYESHA 5
./data/ayesha baby
./data/AYSHA PAT HOUSE 32
./data/babydoll
./data/babydoll 16
./data/babydoll 22
./data/BALAJI SPARK
./data/BANDHAN
./data/BATIK
./data/BATIK KAPIL
./data/BATIK PRIYANKA
./data/BREEZER
./data/BREZZER
./data/bull bull
./data/Celebration 2
./data/chief guest
./data/chief guest2
./data/classy cotton
./data/cotton plus 3
./data/DD 2
./data/DD 3
./data/DD 4
./data/DD 5
./data/DD 6
./data/DD 7
./data/DD 8
./data/DD 9
./data/DEEPTEX BANDNI
./data/DEEPTEX BANDNI CHUNARI
./data/DEVI BATIK
./data/dolly 11
./data/DOLLY 13
./data/DOLLY 15
./data/DOLLY 19
./data/DOLLY BATIK
./data/elegant ayesha 3
./data/feelings
./data/GANESA 13
./data/GANESA PATIALA 1
./data/GANESA PATIALA 2
./data/GAZAL
./data/HOT SHOT
./data/HOTSTAR
./data/ISHQ E AYESHA 4
./data/jalwa 1
./data/jalwa 2
./data/jodha
./data/jodha 2
./data/jugni
./data/KANISHKA

In [2]:
price=np.loadtxt('price.txt')
print price

[[ 495.    1.    1.    0.]
 [ 405.    1.    1.    0.]
 [ 640.    0.    2.    0.]
 [ 540.    1.    1.    0.]
 [ 485.    1.   10.    0.]
 [ 310.    1.    2.    0.]
 [ 310.    1.    2.    1.]
 [ 350.    1.    2.    0.]
 [ 870.    0.   10.    1.]
 [ 830.    0.   10.    1.]
 [ 535.    1.   10.    1.]
 [ 914.    0.   10.    0.]
 [ 555.    1.    1.    1.]
 [ 535.    1.    1.    1.]
 [ 555.    1.   10.    0.]
 [ 465.    0.   10.    0.]
 [ 310.    1.    2.    0.]
 [ 460.    1.    0.    0.]
 [ 430.    1.    0.    1.]
 [ 405.    1.    0.    0.]
 [ 345.    0.    2.    1.]
 [ 685.    1.   10.    0.]
 [ 430.    1.   10.    0.]
 [ 610.    0.   10.    1.]
 [ 400.    1.    2.    0.]
 [ 385.    1.    2.    0.]
 [ 320.    1.    2.    0.]
 [ 605.    0.   10.    0.]
 [ 455.    1.   10.    0.]
 [ 455.    1.   10.    1.]
 [ 450.    1.    1.    0.]
 [ 445.    1.    1.    0.]
 [ 445.    1.    1.    1.]
 [ 445.    1.    1.    0.]
 [ 455.    1.   10.    0.]
 [ 455.    1.   10.    0.]
 [ 345.    1.    0.    0.]
 

In [3]:
from PIL import Image
im=[]
p=[]
w=[]
h=[]
c=[]
q=0
for f in folder:
    files=glob.glob(f+'/*.jpg')
    for j in files:
        img=Image.open(j)
        #print img.size
        img=img.resize((50,50), Image.ANTIALIAS)
        newim=np.asarray(img)
        '''break
        b=plt.imread(i)
        '''
        b=newim.flatten()
        im.append(b)
        p.append(price[q][0])
        w.append(price[q][1])
        h.append(price[q][2])
        c.append(price[q][3])
    q=q+1

print im[0],p[0],w[0],h[0],c[0]

[255 255 255 ..., 255 255 255] 495.0 1.0 1.0 0.0


In [19]:
print np.shape(im)

(1756, 7500)


In [20]:
print len(im)
from sklearn.svm import SVR
svr = SVR(kernel='rbf', C=1e3, gamma=0.1)

1756


In [28]:
oe1=0.0
oe2=0.0
for i in range(10):
    from keras.models import Sequential
    from keras.layers import Dense, Activation
    m=Sequential()
    m.add(Dense(1000,input_dim=7500))
    m.add(Activation('relu'))
    m.add(Dense(100))
    m.add(Activation('relu'))
    m.add(Dense(1))
    m.add(Activation('relu'))

    m.compile(loss='mean_absolute_percentage_error',optimizer='sgd')
    
    #print len(im)
    from sklearn.svm import SVR
    svr = SVR(kernel='rbf', C=1e3, gamma=0.1)

    
    trainx=[]
    trainy=[]
    testx=[]
    testy=[]
    for j in range(1750):
        if j < i*175 or j>=i*175 + 175:
            temp=[]
            for l in range(7500):
                temp.append(float(im[j][l])/255)
            trainx.append(temp)
            trainy.append([p[j]])
    for j in range(i*175,i*175 + 175):
        temp=[]
        for l in range(7500):
            temp.append(float(im[j][l])/255)
        testx.append(temp)
    #testx=[im[x]/255 for x in range(i*175,i*175 + 175)]
    for j in range(i*175,i*175 + 175):
        testy.append(p[j])
    #testy=[p[x] for x in range(i*175,i*175 + 175)]    
    print np.shape(trainx)
    m.fit(trainx,trainy, epochs=10, batch_size=32)
    tp=m.predict(trainx,batch_size=16)
    #print len(tp)
    newtrainx=[]
    k=0
    #print len(tp)
    for j in range(1750):
        if j < i*175 or j>=i*175 + 175:
            b=[tp[k][0]]
            b.append(w[j])
            b.append(h[j])
            b.append(c[j])
            newtrainx.append(b)
            k=k+1
    svr.fit(newtrainx,trainy)
    tp=m.predict(testx,batch_size=32)
    acc=0.0
    #print ty
    for j in range(len(tp)):
        acc+=(abs(testy[j]-tp[j])/testy[j])*100
    acc=acc/len(tp)
    print acc
    oe1+=acc
    
    newtest=[]
    k=0
    for j in range(i*175,i*175+175):
        b=[tp[k][0]]
        k=k+1
        b.append(w[j])
        b.append(h[j])
        b.append(c[j])
        newtest.append(b)
    ty=svr.predict(newtest)
    acc=0.0
    #print ty
    for j in range(len(ty)):
        acc+=(abs(testy[j]-ty[j])/testy[j])*100
    acc=acc/len(ty)
    print acc
    oe2+=acc

(1575, 7500)
Epoch 1/10
1575/1575 [==============================] - 2s - loss: 44.3110      

In [29]:
print oe1/10
print oe2/10

[ 41.54169846]
21.4298103053


In [30]:
oe1=0.0
oe2=0.0
for i in range(10):
    from keras.models import Sequential
    from keras.layers import Dense, Activation
    m=Sequential()
    m.add(Dense(1000,input_dim=7500))
    m.add(Activation('relu'))
    m.add(Dense(100))
    m.add(Activation('relu'))
    m.add(Dense(1))
    m.add(Activation('relu'))

    m.compile(loss='mean_absolute_percentage_error',optimizer='adam')
    
    #print len(im)
    from sklearn.svm import SVR
    svr = SVR(kernel='rbf', C=1e3, gamma=0.1)

    
    trainx=[]
    trainy=[]
    testx=[]
    testy=[]
    for j in range(1750):
        if j < i*175 or j>=i*175 + 175:
            temp=[]
            for l in range(7500):
                temp.append(float(im[j][l])/255)
            trainx.append(temp)
            trainy.append([p[j]])
    for j in range(i*175,i*175 + 175):
        temp=[]
        for l in range(7500):
            temp.append(float(im[j][l])/255)
        testx.append(temp)
    #testx=[im[x]/255 for x in range(i*175,i*175 + 175)]
    for j in range(i*175,i*175 + 175):
        testy.append(p[j])
    #testy=[p[x] for x in range(i*175,i*175 + 175)]    
    print np.shape(trainx)
    m.fit(trainx,trainy, epochs=10, batch_size=32)
    tp=m.predict(trainx,batch_size=16)
    #print len(tp)
    newtrainx=[]
    k=0
    #print len(tp)
    for j in range(1750):
        if j < i*175 or j>=i*175 + 175:
            b=[tp[k][0]]
            b.append(w[j])
            b.append(h[j])
            b.append(c[j])
            newtrainx.append(b)
            k=k+1
    svr.fit(newtrainx,trainy)
    tp=m.predict(testx,batch_size=32)
    acc=0.0
    #print ty
    for j in range(len(tp)):
        acc+=(abs(testy[j]-tp[j])/testy[j])*100
    acc=acc/len(tp)
    print acc
    oe1+=acc
    
    newtest=[]
    k=0
    for j in range(i*175,i*175+175):
        b=[tp[k][0]]
        k=k+1
        b.append(w[j])
        b.append(h[j])
        b.append(c[j])
        newtest.append(b)
    ty=svr.predict(newtest)
    acc=0.0
    #print ty
    for j in range(len(ty)):
        acc+=(abs(testy[j]-ty[j])/testy[j])*100
    acc=acc/len(ty)
    print acc
    oe2+=acc

(1575, 7500)
Epoch 1/10
  96/1575 [>.............................] - ETA: 99s - loss: 85.7136 

/root/anaconda2/lib/python2.7/site-packages/keras/callbacks.py:118: UserWarning: Method on_batch_end() is slow compared to the batch update (0.622259). Check your callbacks.
  % delta_t_median)


1575/1575 [==============================] - 11s - loss: 33.5851     

In [31]:
print oe1/10
print oe2/10

[ 34.60269547]
23.1050259936
