In [3]:
import glob
import numpy as np
from pprint import pprint 
folder=glob.glob("./lol/*")
folder=sorted(folder, key=lambda s: s.lower())
for f in folder:
    print f
print len(folder)

./lol/DD 5
./lol/DD 6
./lol/DD7
./lol/DD8
./lol/DD9
./lol/DEEPTEX BANDI CHUNARI
./lol/DEEPTEX BANDNI
./lol/DEVI BATIK
./lol/DOLLY
./lol/dolly 11
./lol/DOLLY 13
./lol/DOLLY 15
./lol/DOLLY BATIK
./lol/elegant ayesha 3
./lol/feelings
./lol/GANESA
./lol/GANESA 13
./lol/ganesa patiala2
./lol/GAZAL
./lol/HOT SHOT
./lol/HOTSTAR
./lol/ISHQ E AYESHA 4
./lol/jalwa 1
./lol/jalwa2
./lol/jodha 2
./lol/KAPIL DD8
./lol/KARISHMA HOUSE
./lol/LOOKWELL RADIANCE
28


In [5]:
price=np.loadtxt('price.txt')
print price

[[ 445.    1.    1.    0.]
 [ 455.    1.   10.    0.]
 [ 455.    1.   10.    0.]
 [ 445.    1.    1.    0.]
 [ 445.    1.    1.    1.]
 [ 345.    1.    0.    0.]
 [ 345.    1.    0.    0.]
 [ 435.    1.    0.    0.]
 [ 561.    1.    1.    0.]
 [ 560.    1.    1.    0.]
 [ 550.    1.    1.    0.]
 [ 545.    1.    1.    0.]
 [ 320.    1.    0.    0.]
 [ 835.    0.   10.    1.]
 [ 425.    0.    1.    0.]
 [ 330.    1.    2.    0.]
 [ 295.    1.    2.    0.]
 [ 320.    1.    2.    0.]
 [ 465.    1.   10.    0.]
 [ 340.    1.    2.    0.]
 [ 450.    1.    1.    0.]
 [ 880.    0.   10.    1.]
 [ 785.    0.   10.    1.]
 [ 785.    0.   10.    1.]
 [ 805.    0.   10.    0.]
 [ 440.    1.   10.    0.]
 [ 620.    0.    1.    0.]
 [ 615.    1.   10.    0.]]


In [6]:
from PIL import Image
im=[]
p=[]
w=[]
h=[]
c=[]
q=0
for f in folder:
    files=glob.glob(f+'/*.jpg')
    for j in files:
        img=Image.open(j)
        #print img.size
        img=img.resize((30,30), Image.ANTIALIAS)
        newim=np.asarray(img)
        '''break
        b=plt.imread(i)
        '''
        b=newim.flatten()
        im.append(b)
        p.append(price[q][0])
        w.append(price[q][1])
        h.append(price[q][2])
        c.append(price[q][3])
    q=q+1

print im[0],p[0],w[0],h[0],c[0]

[ 74  55  28 ..., 253  67  96] 445.0 1.0 1.0 0.0


In [7]:
print len(im)
from sklearn.svm import SVR
svr = SVR(kernel='rbf', C=1e3, gamma=0.1)

380


In [14]:
oe1=0.0
oe2=0.0
size=len(im)
part=size/4
for i in range(4):
    from keras.models import Sequential
    from keras.layers import Dense, Activation
    m=Sequential()
    m.add(Dense(600,input_dim=2700))
    m.add(Activation('relu'))
    m.add(Dense(100))
    m.add(Activation('relu'))
    m.add(Dense(1))
    m.add(Activation('relu'))

    m.compile(loss='mean_absolute_percentage_error',optimizer='sgd')
    
    #print len(im)
    from sklearn.svm import SVR
    svr = SVR(kernel='rbf', C=1e3, gamma=0.1)

    
    trainx=[]
    trainy=[]
    testx=[]
    testy=[]
    for j in range(size):
        if j < i*part or j>=i*part + part:
            temp=[]
            for l in range(2700):
                temp.append(float(im[j][l])/255)
            trainx.append(temp)
            trainy.append([p[j]])
    for j in range(i*part,i*part + part):
        temp=[]
        for l in range(2700):
            temp.append(float(im[j][l])/255)
        testx.append(temp)
    #testx=[im[x]/255 for x in range(i*175,i*175 + 175)]
    for j in range(i*part,(i+1)*part):
        testy.append(p[j])
    #testy=[p[x] for x in range(i*175,i*175 + 175)]    
    print np.shape(trainx)
    m.fit(trainx,trainy, epochs=10, batch_size=32)
    tp=m.predict(trainx,batch_size=16)
    #print len(tp)
    newtrainx=[]
    k=0
    #print len(tp)
    for j in range(size):
        if j < i*part or j>=(i+1)*part:
            b=[tp[k][0]]
            b.append(w[j])
            b.append(h[j])
            b.append(c[j])
            newtrainx.append(b)
            k=k+1
    svr.fit(newtrainx,trainy)
    tp=m.predict(testx,batch_size=32)
    acc=0.0
    #print ty
    for j in range(len(tp)):
        acc+=(abs(testy[j]-tp[j])/testy[j])*100
    acc=acc/len(tp)
    print acc
    oe1+=acc
    
    newtest=[]
    k=0
    for j in range(i*part,(i+1)*part):
        b=[tp[k][0]]
        k=k+1
        b.append(w[j])
        b.append(h[j])
        b.append(c[j])
        newtest.append(b)
    ty=svr.predict(newtest)
    acc=0.0
    #print ty
    for j in range(len(ty)):
        acc+=(abs(testy[j]-ty[j])/testy[j])*100
    acc=acc/len(ty)
    print acc
    oe2+=acc

(285, 2700)
Epoch 1/10
285/285 [==============================] - 0s - loss: 98.4117     
Epoch 2/10
285/285 [==============================] - 0s - loss: 88.1291     
Epoch 3/10
285/285 [==============================] - 0s - loss: 36.1444     
Epoch 4/10
285/285 [==============================] - 0s - loss: 31.3813     
Epoch 5/10
285/2

In [15]:
print oe1/4
print oe2/4

[ 29.95872498]
35.5724181824


In [16]:
oe1=0.0
oe2=0.0
size=len(im)
part=size/4
for i in range(4):
    from keras.models import Sequential
    from keras.layers import Dense, Activation
    m=Sequential()
    m.add(Dense(600,input_dim=2700))
    m.add(Activation('relu'))
    m.add(Dense(100))
    m.add(Activation('relu'))
    m.add(Dense(1))
    m.add(Activation('relu'))

    m.compile(loss='mean_absolute_percentage_error',optimizer='adam')#best
    
    #print len(im)
    from sklearn.svm import SVR
    svr = SVR(kernel='rbf', C=1e3, gamma=0.1)

    
    trainx=[]
    trainy=[]
    testx=[]
    testy=[]
    for j in range(size):
        if j < i*part or j>=i*part + part:
            temp=[]
            for l in range(2700):
                temp.append(float(im[j][l])/255)
            trainx.append(temp)
            trainy.append([p[j]])
    for j in range(i*part,i*part + part):
        temp=[]
        for l in range(2700):
            temp.append(float(im[j][l])/255)
        testx.append(temp)
    #testx=[im[x]/255 for x in range(i*175,i*175 + 175)]
    for j in range(i*part,(i+1)*part):
        testy.append(p[j])
    #testy=[p[x] for x in range(i*175,i*175 + 175)]    
    print np.shape(trainx)
    m.fit(trainx,trainy, epochs=10, batch_size=32)
    tp=m.predict(trainx,batch_size=16)
    #print len(tp)
    newtrainx=[]
    k=0
    #print len(tp)
    for j in range(size):
        if j < i*part or j>=(i+1)*part:
            b=[tp[k][0]]
            b.append(w[j])
            b.append(h[j])
            b.append(c[j])
            newtrainx.append(b)
            k=k+1
    svr.fit(newtrainx,trainy)
    tp=m.predict(testx,batch_size=32)
    acc=0.0
    #print ty
    for j in range(len(tp)):
        acc+=(abs(testy[j]-tp[j])/testy[j])*100
    acc=acc/len(tp)
    print acc
    oe1+=acc
    
    newtest=[]
    k=0
    for j in range(i*part,(i+1)*part):
        b=[tp[k][0]]
        k=k+1
        b.append(w[j])
        b.append(h[j])
        b.append(c[j])
        newtest.append(b)
    ty=svr.predict(newtest)
    acc=0.0
    #print ty
    for j in range(len(ty)):
        acc+=(abs(testy[j]-ty[j])/testy[j])*100
    acc=acc/len(ty)
    print acc
    oe2+=acc

(285, 2700)
Epoch 1/10
285/285 [==============================] - 0s - loss: 82.1126     
Epoch 2/10
285/285 [==============================] - 0s - loss: 37.3470     
Epoch 3/10
285/285 [==============================] - 0s - loss: 32.4191     

In [18]:
print oe1/4
print oe2/4

[ 29.87824249]
34.9050967613


In [80]:
print ty


[ 792.4425309   768.53839033  676.59174491  592.4112082   640.05853641
  781.38047251  811.96914688  776.91484929  809.50655874  331.00476436
  371.62278954  403.5966027   362.26467941  324.3859366   348.99773769
  350.49588398  367.26611185  335.4591817   328.46266748  394.23117083
  400.09292775  369.55942696  394.25884565  324.96797658  731.43432883
  657.80205995  828.11365244  647.29142384  684.81288602  981.21289267
  815.75002174  543.8716752   491.49937942  360.94420948  356.06939583
  327.11756646  374.41022646  361.90935003  382.36761088  370.330859
  555.46375483  911.82292724  585.65908578  507.76508145  709.18474183
  782.92430192  635.22966112  699.95241884  690.09140519  624.15555223
  563.75890059  790.78553547  749.99203309  597.20763552  355.28219253
  487.80924209  882.84409368  706.21991354  786.88590381  625.17633303
  486.5990475   694.4067499   846.84220612  684.79505767  750.00129679
  344.1390945   510.95706964  378.12712319  461.2799192   519.76022449
  332.47

In [81]:
print testy

[810.0, 810.0, 810.0, 810.0, 810.0, 810.0, 810.0, 810.0, 810.0, 370.0, 370.0, 370.0, 370.0, 370.0, 370.0, 370.0, 370.0, 320.0, 320.0, 320.0, 320.0, 320.0, 320.0, 320.0, 610.0, 610.0, 610.0, 610.0, 610.0, 610.0, 610.0, 610.0, 610.0, 360.0, 360.0, 360.0, 360.0, 360.0, 360.0, 360.0, 260.0, 260.0, 260.0, 260.0, 260.0, 260.0, 260.0, 260.0, 260.0, 260.0, 260.0, 260.0, 260.0, 260.0, 260.0, 260.0, 260.0, 260.0, 260.0, 260.0, 260.0, 260.0, 260.0, 260.0, 260.0, 260.0, 260.0, 330.0, 330.0, 330.0, 330.0, 330.0, 330.0, 330.0, 330.0, 330.0, 330.0, 330.0, 250.0, 250.0, 250.0, 250.0, 250.0, 250.0, 250.0, 250.0, 250.0, 250.0, 250.0, 250.0, 685.0, 685.0, 685.0, 685.0, 685.0, 685.0, 685.0, 685.0, 685.0, 685.0, 685.0, 685.0, 450.0, 450.0, 450.0, 450.0, 450.0, 450.0, 450.0, 450.0, 450.0, 450.0, 450.0, 450.0, 450.0, 285.0, 285.0, 285.0, 285.0, 285.0, 285.0, 285.0, 285.0, 285.0, 285.0, 285.0, 285.0, 285.0, 285.0, 285.0, 360.0, 360.0, 360.0, 360.0, 360.0, 360.0, 360.0, 360.0, 360.0, 360.0, 360.0, 360.0, 360.0

In [28]:
j=0
for k in range(50,500):
    j=0
    for i in range(len(testy)):
        if(testy[i]-ty[i] >= k):
            j+=1
    print k, ",", j

50 , 67
51 , 67
52 , 67
53 , 67
54 , 67
55 , 67
56 , 67
57 , 67
58 , 67
59 , 67
60 , 67
61 , 67
62 , 67
63 , 67
64 , 67
65 , 67
66 , 67
67 , 67
68 , 67
69 , 67
70 , 67
71 , 67
72 , 67
73 , 67
74 , 67
75 , 67
76 , 67
77 , 67
78 , 67
79 , 66
80 , 66
81 , 66
82 , 66
83 , 66
84 , 66
85 , 66
86 , 66
87 , 66
88 , 66
89 , 66
90 , 66
91 , 66
92 , 66
93 , 66
94 , 66
95 , 66
96 , 66
97 , 66
98 , 66
99 , 66
100 , 66
101 , 66
102 , 66
103 , 66
104 , 66
105 , 66
106 , 66
107 , 66
108 , 66
109 , 66
110 , 66
111 , 66
112 , 66
113 , 66
114 , 66
115 , 66
116 , 66
117 , 66
118 , 66
119 , 66
120 , 66
121 , 66
122 , 66
123 , 66
124 , 66
125 , 66
126 , 66
127 , 66
128 , 66
129 , 66
130 , 65
131 , 65
132 , 65
133 , 65
134 , 65
135 , 64
136 , 64
137 , 64
138 , 64
139 , 64
140 , 64
141 , 64
142 , 64
143 , 64
144 , 64
145 , 64
146 , 64
147 , 64
148 , 64
149 , 64
150 , 64
151 , 64
152 , 64
153 , 63
154 , 63
155 , 63
156 , 62
157 , 62
158 , 62
159 , 62
160 , 62
161 , 61
162 , 61
163 , 61
164 , 61
165 , 61
166 , 