In [1]:
import glob
import numpy as np
from pprint import pprint 
folder=glob.glob("./lol/*")
folder=sorted(folder, key=lambda s: s.lower())
for f in folder:
    print f
print len(folder)

./lol/DD 5
./lol/DD 6
./lol/DD7
./lol/DD8
./lol/DD9
./lol/DEEPTEX BANDI CHUNARI
./lol/DEEPTEX BANDNI
./lol/DEVI BATIK
./lol/DOLLY
./lol/dolly 11
./lol/DOLLY 13
./lol/DOLLY 15
./lol/DOLLY BATIK
./lol/elegant ayesha 3
./lol/feelings
./lol/GANESA
./lol/GANESA 13
./lol/ganesa patiala2
./lol/GAZAL
./lol/HOT SHOT
./lol/HOTSTAR
./lol/ISHQ E AYESHA 4
./lol/jalwa 1
./lol/jalwa2
./lol/jodha 2
./lol/KAPIL DD8
./lol/KARISHMA HOUSE
./lol/LOOKWELL RADIANCE
28


In [2]:
price=np.loadtxt('price.txt')
print price

[[ 445.    1.    1.    0.]
 [ 455.    1.   10.    0.]
 [ 455.    1.   10.    0.]
 [ 445.    1.    1.    0.]
 [ 445.    1.    1.    1.]
 [ 345.    1.    0.    0.]
 [ 345.    1.    0.    0.]
 [ 435.    1.    0.    0.]
 [ 561.    1.    1.    0.]
 [ 560.    1.    1.    0.]
 [ 550.    1.    1.    0.]
 [ 545.    1.    1.    0.]
 [ 320.    1.    0.    0.]
 [ 835.    0.   10.    1.]
 [ 425.    0.    1.    0.]
 [ 330.    1.    2.    0.]
 [ 295.    1.    2.    0.]
 [ 320.    1.    2.    0.]
 [ 465.    1.   10.    0.]
 [ 340.    1.    2.    0.]
 [ 450.    1.    1.    0.]
 [ 880.    0.   10.    1.]
 [ 785.    0.   10.    1.]
 [ 785.    0.   10.    1.]
 [ 805.    0.   10.    0.]
 [ 440.    1.   10.    0.]
 [ 620.    0.    1.    0.]
 [ 615.    1.   10.    0.]]


In [3]:
from PIL import Image
im=[]
p=[]
w=[]
h=[]
c=[]
q=0
for f in folder:
    files=glob.glob(f+'/*.jpg')
    for j in files:
        img=Image.open(j)
        #print img.size
        img=img.resize((50,50), Image.ANTIALIAS)
        newim=np.asarray(img)
        '''break
        b=plt.imread(i)
        '''
        b=newim.flatten()
        im.append(b)
        p.append(price[q][0])
        w.append(price[q][1])
        h.append(price[q][2])
        c.append(price[q][3])
    q=q+1

print im[0],p[0],w[0],h[0],c[0]

[ 69  50  25 ..., 242  76  93] 445.0 1.0 1.0 0.0


In [4]:
print len(im)
from sklearn.svm import SVR
svr = SVR(kernel='rbf', C=1e3, gamma=0.1)

380


In [8]:
oe1=0.0
oe2=0.0
size=len(im)
part=size/4
for i in range(4):
    from keras.models import Sequential
    from keras.layers import Dense, Activation
    m=Sequential()
    m.add(Dense(1200,input_dim=7500))
    m.add(Activation('sigmoid'))
    m.add(Dense(400))
    m.add(Activation('relu'))
    m.add(Dense(30))
    m.add(Activation('relu'))
    m.add(Dense(1))
    m.add(Activation('relu'))

    m.compile(loss='mean_absolute_percentage_error',optimizer='adam')
    
    #print len(im)
    from sklearn.svm import SVR
    svr = SVR(kernel='rbf', C=1e3, gamma=0.1)

    
    trainx=[]
    trainy=[]
    testx=[]
    testy=[]
    for j in range(size):
        if j < i*part or j>=i*part + part:
            temp=[]
            for l in range(7500):
                temp.append(float(im[j][l])/255)
            trainx.append(temp)
            trainy.append([p[j]])
    for j in range(i*part,i*part + part):
        temp=[]
        for l in range(7500):
            temp.append(float(im[j][l])/255)
        testx.append(temp)
    #testx=[im[x]/255 for x in range(i*175,i*175 + 175)]
    for j in range(i*part,(i+1)*part):
        testy.append(p[j])
    #testy=[p[x] for x in range(i*175,i*175 + 175)]    
    print np.shape(trainx)
    m.fit(trainx,trainy, epochs=15, batch_size=16)
    tp=m.predict(trainx,batch_size=16)
    #print len(tp)
    newtrainx=[]
    k=0
    #print len(tp)
    for j in range(size):
        if j < i*part or j>=(i+1)*part:
            b=[tp[k][0]]
            b.append(w[j])
            b.append(h[j])
            b.append(c[j])
            newtrainx.append(b)
            k=k+1
    svr.fit(newtrainx,trainy)
    tp=m.predict(testx,batch_size=32)
    acc=0.0
    #print ty
    for j in range(len(tp)):
        acc+=(abs(testy[j]-tp[j])/testy[j])*100
    acc=acc/len(tp)
    print acc
    oe1+=acc
    
    newtest=[]
    k=0
    for j in range(i*part,(i+1)*part):
        b=[tp[k][0]]
        k=k+1
        b.append(w[j])
        b.append(h[j])
        b.append(c[j])
        newtest.append(b)
    ty=svr.predict(newtest)
    acc=0.0
    #print ty
    for j in range(len(ty)):
        acc+=(abs(testy[j]-ty[j])/testy[j])*100
    acc=acc/len(ty)
    print acc
    oe2+=acc

(285, 7500)
Epoch 1/15
285/285 [==============================] - 2s - loss: 85.6285     

In [9]:
print oe1/4
print oe2/4

[ 40.3893013]
31.6945675042


In [17]:
oe1=0.0
oe2=0.0
size=len(im)
part=size/4
for i in range(4):
    from keras.models import Sequential
    from keras.layers import Dense, Activation
    m=Sequential()
    m.add(Dense(1200,input_dim=7500))
    m.add(Activation('relu'))
    m.add(Dense(400))
    m.add(Activation('relu'))
    m.add(Dense(30))
    m.add(Activation('relu'))
    m.add(Dense(1))
    m.add(Activation('relu'))

    m.compile(loss='mean_absolute_percentage_error',optimizer='adam')
    
    #print len(im)
    from sklearn.svm import SVR
    svr = SVR(kernel='rbf', C=1e3, gamma=0.1)

    
    trainx=[]
    trainy=[]
    testx=[]
    testy=[]
    for j in range(size):
        if j < i*part or j>=i*part + part:
            temp=[]
            for l in range(7500):
                temp.append(float(im[j][l])/255)
            trainx.append(temp)
            trainy.append([p[j]])
    for j in range(i*part,i*part + part):
        temp=[]
        for l in range(7500):
            temp.append(float(im[j][l])/255)
        testx.append(temp)
    #testx=[im[x]/255 for x in range(i*175,i*175 + 175)]
    for j in range(i*part,(i+1)*part):
        testy.append(p[j])
    #testy=[p[x] for x in range(i*175,i*175 + 175)]    
    print np.shape(trainx)
    m.fit(trainx,trainy, epochs=15, batch_size=16)
    tp=m.predict(trainx,batch_size=16)
    #print len(tp)
    newtrainx=[]
    k=0
    #print len(tp)
    for j in range(size):
        if j < i*part or j>=(i+1)*part:
            b=[tp[k][0]]
            b.append(w[j])
            b.append(h[j])
            b.append(c[j])
            newtrainx.append(b)
            k=k+1
    svr.fit(newtrainx,trainy)
    tp=m.predict(testx,batch_size=32)
    acc=0.0
    #print ty
    for j in range(len(tp)):
        acc+=(abs(testy[j]-tp[j])/testy[j])*100
    acc=acc/len(tp)
    print acc
    oe1+=acc
    
    newtest=[]
    k=0
    for j in range(i*part,(i+1)*part):
        b=[tp[k][0]]
        k=k+1
        b.append(w[j])
        b.append(h[j])
        b.append(c[j])
        newtest.append(b)
    ty=svr.predict(newtest)
    acc=0.0
    #print ty
    for j in range(len(ty)):
        acc+=(abs(testy[j]-ty[j])/testy[j])*100
    acc=acc/len(ty)
    print "with svr",acc
    oe2+=acc

(285, 7500)
Epoch 1/15
285/285 [==============================] - 2s - loss: 46.9852     

In [19]:
print oe1/4
print oe2/4

[ 30.3257618]
33.3990866436


In [20]:
print ty

[ 560.26011026  446.54003725  496.29974782  507.10572064  555.86066905
  446.20419664  378.55733539  597.66979574  509.46539018  450.60997447
  457.33434054  457.33944279  465.91586604  457.96879631  446.52815628
  453.06589604  459.9988921   445.84296261  775.10394354  452.1427458
  459.08778776  482.00207922  456.55206183  484.5444711   545.15874152
  444.66989654  438.22490372  452.69912144  444.69842168  452.019185
  450.92869647  446.62398318  455.45648779  448.50904233  444.66987745
  458.54287252  450.38611176  462.50390112  446.06859118  453.38838499
  444.73452721  449.22558881  451.39897883  449.90361036  450.85348253
  444.67489967  444.65881581  444.66453112  471.8567661   469.56972713
  453.96564706  775.08749002  690.93789052  444.9064145   448.28059988
  452.22482513  451.4782826   523.72393822  454.03955074  782.46661794
  440.97116751  444.67193257  471.85226676  444.68979016  464.81459284
  452.90329844  457.72291607  447.68967236  459.25108917  448.86417374
  454.802

In [21]:
print testy

[450.0, 450.0, 450.0, 450.0, 450.0, 450.0, 450.0, 450.0, 450.0, 880.0, 880.0, 880.0, 880.0, 880.0, 880.0, 880.0, 880.0, 880.0, 880.0, 880.0, 785.0, 785.0, 785.0, 785.0, 785.0, 785.0, 785.0, 785.0, 785.0, 785.0, 785.0, 785.0, 785.0, 785.0, 785.0, 785.0, 785.0, 785.0, 785.0, 785.0, 785.0, 785.0, 785.0, 785.0, 785.0, 805.0, 805.0, 805.0, 805.0, 805.0, 805.0, 805.0, 805.0, 805.0, 805.0, 805.0, 805.0, 805.0, 805.0, 805.0, 805.0, 440.0, 440.0, 440.0, 440.0, 440.0, 440.0, 440.0, 440.0, 440.0, 440.0, 440.0, 440.0, 620.0, 620.0, 620.0, 620.0, 620.0, 620.0, 620.0, 620.0, 620.0, 620.0, 620.0, 620.0, 620.0, 620.0, 615.0, 615.0, 615.0, 615.0, 615.0, 615.0, 615.0, 615.0]
